### ISSUE TITLE
Cassandra and uwsgi timeout needs replacement on native setup

### ISSUE THREAD

**Issue by cosmin-ionita** [catalinif/webtierbench#1]
We need to update the start_benchmark.sh (on native setup) script to replace the sleep command with the actual loop that waits until a specific port (on cassandra and on uwsgi) is opened.

**Comment by ADiea** [comment]
Fixed with 35b7df74d56c4e2658671fbcebad63c0ff215aa5 1850284ba117865d1be8d1da8ee78f37740bcd33 and bd17ef7d8f0870a04f4078d88aa3510543862ed1
